### ISSUE TITLE
Extract the archive functionality into a free tool.

### ISSUE THREAD

**Issue by stevepolitodesign** [stevepolitodesign/my_site_archive#103]
**To-do**
- [x] Limit them to a certain amount of archives, then redirect them to sign up.
  - [ ] Upon sign up, associate their guest account with the account created if possible.
- [x] Need to use a CAPTCHA and/or rate limit users.
- [x] Create and test job to purge old archives owned by a guest user. Make sure to account for any edge cases where a guest user somehow is a paying customer. 
- [x] Add a CTA on the homepage
- [x] Add a link to the navigation
- [x] Add metadata
  - [x] Be deliberate with the page title and url. Something like "free website screenshot generator", "free dns lookup", or "free website archive tool"
- [x] Add to sitemap

**Questions**
- Should I encourage users to share their archives? If so, this means I almost certainly cannot delete them. 

**Post Laucnh**

- [ ] Regnerate sitemap
- [ ] Add `rails purge_guest_accounts:perform` to cron
